# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OneOnOneSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#  use_frameworks!
#  plugin 'cocoapods-pod-sign'
#  skip_pod_bundle_sign
  
  def imVersion
    '9.12.0'
  end

  def rtcVersion
    '5.4.0'
  end

  #公共库(被多余一个组件引用，可定义多个)
  def imSDKPod
    pod 'NIMSDK_LITE',imVersion
  end

  def rtcBasicPod
    pod 'NERtcSDK/RtcBasic',rtcVersion
  end


def thirdPartyLibraryPod
  pod 'SDWebImage', '5.7.1'
  pod 'AFNetworking', '4.0'
  pod 'Masonry'
  pod 'Toast'
end

  imSDKPod
  rtcBasicPod
  thirdPartyLibraryPod
  
#源码依赖
pod 'NEUIKit', :path => '../NEUIKit/NEUIKit.podspec'
pod 'LottieSwift', :path => '../lottie/LottieSwift.podspec'
pod 'NESocialUIKit', :path => '../NESocialUIKit/NESocialUIKit.podspec'


# 1v1
pod 'NEOneOnOneKit', :path => '../OneOnOneKit/NEOneOnOneKit.podspec'
pod 'NEOneOnOneUIKit', :path => '../OneOnOneUIKit/NEOneOnOneUIKit.podspec'
pod 'NEOneOnOneChatUIKit', :path => '../OneOnOneChatUIKit/NEOneOnOneChatUIKit.podspec'
pod 'NEConversationUIKit', :path => '../IMUIKit/NEConversationUIKit/NEConversationUIKit.podspec'
pod 'NEChatUIKit',:path => '../IMUIKit/NEChatUIKit/NEChatUIKit.podspec'

#设置
pod 'FaceUnity', :path => '../FaceUnity/FaceUnity.podspec'

#登录
pod 'NELoginSample',:path => '../NELoginSample/NELoginSample.podspec'

#远端依赖
pod 'NERoomKit/Special_All', '1.18.0'
pod 'IHProgressHUD'
pod 'NERtcCallUIKit', '2.0.1'
pod 'NERtcCallKit', '2.0.1'

pod 'NECommonUIKit','9.6.1'
pod 'NECommonKit','9.6.0'
#pod 'NEConversationUIKit','9.6.1'
#pod 'NEChatUIKit','9.6.1'
pod 'NECoreIMKit','9.6.1'
pod 'NECoreKit','9.6.0'

#地图插件
pod 'NEMapKit', '9.6.0'

end

# ---------------------------- 公用钩子处理 ----------------------------
post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
  end
  # M1 模拟器运行打开一下代码
  installer.pods_project.build_configurations.each do |config|
     config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
   end
end
